import type { V2CanvasDesign } from "./types-v2";

/** Hardcoded demo design — no Supabase, no network calls. */
export const INITIAL_DESIGN: V2CanvasDesign = {
  width: 390,
  height: 1200,
  background: "linear-gradient(180deg, #0f0a1e 0%, #1a0d2e 50%, #0f0a1e 100%)",
  elements: [
    // ── Fondo hero image ──────────────────────────────────────────────────
    {
      id: "hero-bg",
      type: "image",
      x: 0,
      y: 0,
      width: 390,
      height: 500,
      zIndex: 1,
      opacity: 0.6,
      locked: true,
      url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=390&q=80",
      objectFit: "cover",
      borderRadius: 0,
    },
    // ── Título principal ──────────────────────────────────────────────────
    {
      id: "main-title",
      type: "text",
      x: 20,
      y: 140,
      width: 350,
      height: 80,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "Valentina García",
      fontFamily: "'Playfair Display', Georgia, serif",
      fontSize: 52,
      fontWeight: "400",
      fontStyle: "italic",
      textAlign: "center",
      color: "#ffffff",
      lineHeight: 1.1,
      letterSpacing: 0,
    },
    // ── Subtítulo / tipo de evento ─────────────────────────────────────────
    {
      id: "event-type",
      type: "text",
      x: 20,
      y: 100,
      width: 350,
      height: 30,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "XV AÑOS",
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 13,
      fontWeight: "600",
      fontStyle: "normal",
      textAlign: "center",
      color: "#c8a96a",
      lineHeight: 1.2,
      letterSpacing: 3,
    },
    // ── Fecha ─────────────────────────────────────────────────────────────
    {
      id: "event-date",
      type: "text",
      x: 45,
      y: 240,
      width: 300,
      height: 36,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "15 de junio de 2025 · 8:00 PM",
      fontFamily: "'Playfair Display', Georgia, serif",
      fontSize: 20,
      fontWeight: "400",
      fontStyle: "italic",
      textAlign: "center",
      color: "#f0e0c0",
      lineHeight: 1.3,
      letterSpacing: 0,
    },
    // ── Decoración top-left ───────────────────────────────────────────────
    {
      id: "deco-top-left",
      type: "decoration",
      x: 0,
      y: 0,
      width: 120,
      height: 120,
      zIndex: 5,
      opacity: 0.7,
      locked: false,
      color: "#c8a96a",
      rotation: 0,
      svgContent: `<svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" width="120" height="120">
        <path d="M10 10 Q60 5 110 10 Q115 60 110 110" stroke="currentColor" stroke-width="1.5" fill="none" opacity="0.6"/>
        <circle cx="20" cy="20" r="3" fill="currentColor" opacity="0.5"/>
        <circle cx="50" cy="12" r="2" fill="currentColor" opacity="0.4"/>
        <circle cx="108" cy="50" r="2" fill="currentColor" opacity="0.4"/>
        <path d="M5 5 C30 2, 60 8, 55 30 C50 52 20 48 5 5" fill="currentColor" opacity="0.08"/>
      </svg>`,
    },
    // ── Decoración top-right ──────────────────────────────────────────────
    {
      id: "deco-top-right",
      type: "decoration",
      x: 270,
      y: 0,
      width: 120,
      height: 120,
      zIndex: 5,
      opacity: 0.7,
      locked: false,
      color: "#c8a96a",
      rotation: 90,
      svgContent: `<svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" width="120" height="120">
        <path d="M10 10 Q60 5 110 10 Q115 60 110 110" stroke="currentColor" stroke-width="1.5" fill="none" opacity="0.6"/>
        <circle cx="20" cy="20" r="3" fill="currentColor" opacity="0.5"/>
        <circle cx="50" cy="12" r="2" fill="currentColor" opacity="0.4"/>
        <circle cx="108" cy="50" r="2" fill="currentColor" opacity="0.4"/>
        <path d="M5 5 C30 2, 60 8, 55 30 C50 52 20 48 5 5" fill="currentColor" opacity="0.08"/>
      </svg>`,
    },
    // ── Mensaje principal ─────────────────────────────────────────────────
    {
      id: "main-message",
      type: "text",
      x: 35,
      y: 540,
      width: 320,
      height: 100,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "Con la gracia de Dios y el amor de mi familia, los invito a celebrar este momento especial en mi vida.",
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 15,
      fontWeight: "400",
      fontStyle: "normal",
      textAlign: "center",
      color: "#f0e0c0",
      lineHeight: 1.5,
      letterSpacing: 0,
    },
    // ── Sección detalles ──────────────────────────────────────────────────
    {
      id: "details-label",
      type: "text",
      x: 20,
      y: 700,
      width: 350,
      height: 36,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "Detalles del evento",
      fontFamily: "'Playfair Display', Georgia, serif",
      fontSize: 28,
      fontWeight: "400",
      fontStyle: "italic",
      textAlign: "center",
      color: "#c8a96a",
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: "address-text",
      type: "text",
      x: 55,
      y: 760,
      width: 280,
      height: 60,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "Salón La Pérgola\nAsunción, Paraguay",
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 14,
      fontWeight: "400",
      fontStyle: "normal",
      textAlign: "center",
      color: "#e0d0c0",
      lineHeight: 1.5,
      letterSpacing: 0,
    },
    // ── Botón RSVP ────────────────────────────────────────────────────────
    {
      id: "rsvp-button",
      type: "text",
      x: 80,
      y: 1090,
      width: 230,
      height: 52,
      zIndex: 10,
      opacity: 1,
      locked: false,
      content: "CONFIRMAR ASISTENCIA",
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 13,
      fontWeight: "700",
      fontStyle: "normal",
      textAlign: "center",
      color: "#ffffff",
      lineHeight: 1.2,
      letterSpacing: 2,
    },
  ],
};
