PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO profiles (id, full_name, email, role, is_active)
VALUES ('kais-system', 'KAIS System', 'admin@kais.local', 'admin_kais', 1);

INSERT OR REPLACE INTO events (
  id,
  owner_id,
  package_key,
  enabled_features,
  disabled_features,
  title,
  event_type,
  hosts_names,
  event_date,
  event_time,
  address,
  google_maps_link,
  whatsapp_phone,
  main_message,
  quinceanera_name,
  parents_names,
  church_name,
  dress_code,
  color_palette,
  theme,
  quince_message,
  parents_message,
  cover_image_url,
  mobile_cover_image_url,
  music_url,
  visual_decorations,
  design_config,
  canvas_design,
  theme_color,
  status,
  guest_mode,
  slug
)
VALUES (
  'event-kenia15',
  'kais-system',
  'luxury',
  '[]',
  '[]',
  'Kenia',
  'quinceaños',
  'Kenia',
  '2026-10-14',
  '20:00',
  'Barrio Maristas Fracción la Loteadora',
  'https://maps.app.goo.gl/aFJZwVr5CyDmjTgp6',
  '595985234672',
  'Deseo que esta noche sea de celebración, y no hay mejor celebración el que se hace con los seres queridos',
  'Kenia',
  'Jorge & Patricia',
  'Catedral Virgen del Rosario',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '#7b1631',
  'publicado',
  'publico',
  'kenia15'
);
